# Generated by Django 6.0.2 on 2026-02-28 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0003_rename_doctor_additionaal_info_doctor_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_code', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=10)),
                ('medicine_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('medicine_Type_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_Type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePurchaseHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_data', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist.medicineinventory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='medicine_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist.medicinetype'),
        ),
    ]
