# Generated by Django 6.0.2 on 2026-03-05 09:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_code', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=30)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('medicine_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('quantity', models.PositiveIntegerField()),
                ('dosage', models.CharField(max_length=50)),
                ('period', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(365)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescriptions', to='reception.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='administration.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacist.medicineinventory')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_bills', to='reception.appointment')),
                ('billed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_bills', to='administration.staff')),
                ('prescriptions', models.ManyToManyField(related_name='bills', to='pharmacist.medicineprescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePurchaseHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='pharmacist.medicineinventory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_purchases', to='administration.staff')),
            ],
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacist.medicinetype'),
        ),
    ]
