# Generated by Django 6.0.2 on 2026-02-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.CreateModel(
            name='Doctor_additionaal_info',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.doctor')),
            ],
        ),
    ]
