# Generated by Django 6.0.2 on 2026-02-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_doctor_specialization_doctor_additionaal_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor_additionaal_info',
            new_name='Doctor_additional_info',
        ),
    ]
