# Generated by Django 5.2.11 on 2026-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('Lab_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lab_test_name', models.CharField(max_length=255)),
                ('Lab_test_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
