# Generated by Django 6.0.2 on 2026-03-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('reception', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('Lab_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lab_test_name', models.CharField(max_length=255)),
                ('Lab_test_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bill', to='reception.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('lab_hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='reception.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='administration.doctor')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='labtechnician.labtesttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('appointment', 'test_type')},
            },
        ),
        migrations.CreateModel(
            name='LabTestReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='labtechnician.labtestprescription')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='administration.staff')),
            ],
        ),
    ]
