# Generated by Django 6.0.2 on 2026-02-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('doctor', '0003_remove_doctorschedule_doctor_delete_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('avail_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_status', models.CharField(choices=[('Fullday', 'Fullday'), ('Morningonly', 'Morning only'), ('Afternoononly', 'Afternoon only'), ('onleave', 'On leave')], max_length=20)),
                ('available_date', models.DateField()),
                ('updated_date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.doctor')),
            ],
            options={
                'db_table': 'doctoravailability',
            },
        ),
    ]
